### ISSUE TITLE
Error in dcast.data.table: Can not cast an empty data.table

### ISSUE THREAD

**Issue by JelenaNA** [martaint/InterCellar#1]
Hi, 

I followed the User Guide and everything works fine until Function-verse where this error appears:

The following `from` values were not present in `x`: biological_process, cellular_component, molecular_function
Warning: Error in dcast.data.table: Can not cast an empty data.table
  [No stack trace available]

Is something missing in the input data or is there some other issue? The input data is a .csv file from CellChat.

Best, 
Jelena

**Comment by martaint** [comment]
Hi Jelena,

thanks for reporting this issue! I think the error here might be related to the choice of databases for the functional annotation. Which sources have you selected?

Best,
Marta

**Comment by JelenaNA** [comment]
Hi Marta, 

Thanks for your quick response!

I tried different sources and possibilities for Gene Ontology and Pathways but halfway through the step it gives me the error and the webpage turns greyish.

**Comment by martaint** [comment]
Uhm, I see! ...quite weird, I don't understand what that could be due to. Could you please try to perform the functional annotation only using Pathways and deselecting Gene Ontology? Would that also fail? And another thing that might be useful for me to have a better idea, could you please send me a screenshot of your "Table view"? The first entries of the table would already be enough! In case you cannot post it here, you can reach me at my email: marta.interlandi@uni-muenster.de

Thank you!!!
Best,
Marta

**Comment by JelenaNA** [comment]
Yes, I also tried only using Pathways, still the same problem.

![InterCellar_TableView](https://user-images.githubusercontent.com/88039961/149957185-b314c093-d380-487f-9555-3aba78519c45.PNG)

I hope this helps!
Best, 
Jelena

**Comment by JelenaNA** [comment]
The error I get using only Pathways:

Warning: Error in dcast.data.table: Can not cast an empty data.table
  [No stack trace available]

**Comment by martaint** [comment]
Hi Jelena,

thanks a lot! I found the problem: it looks like you're using mouse data, right? Unfortunately InterCellar only supports human genes for now :( 
It throws an error because it cannot recognize any gene name and thus cannot perform the annotation :(
One easy fix would be mapping your mouse genes to their human orthologs either before using CellChat, or after. Then, your input data will contain human genes and everything should work out fine!

Sorry for the inconvenience!!!
Let me know if this solved the problem :)

Best,
Marta
